# Generated by Django 6.0.6 on 2026-06-12 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlType', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('lastVerified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('knownAs', models.CharField(blank=True, max_length=255, null=True)),
                ('wikiUrl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musicianWikiUrl', to='services.externalurl')),
            ],
        ),
        migrations.CreateModel(
            name='Canticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('knownAs', models.CharField(max_length=255)),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.musician')),
            ],
        ),
        migrations.CreateModel(
            name='Anthem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('knownAs', models.CharField(blank=True, max_length=255, null=True)),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.musician')),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('knownAs', models.CharField(max_length=255)),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.musician')),
            ],
        ),
        migrations.CreateModel(
            name='MusicList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anthem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.anthem')),
                ('canticles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.canticles')),
                ('responses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.responses')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('townCity', models.CharField(max_length=50)),
                ('map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venueMap', to='services.externalurl')),
                ('wikiUrl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venueWikiUrl', to='services.externalurl')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDateTime', models.DateTimeField()),
                ('choir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviceChoir', to='services.choir')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.musician')),
                ('musicList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.musiclist')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceVenue', to='services.venue')),
            ],
        ),
        migrations.AddField(
            model_name='choir',
            name='homeVenue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.venue'),
        ),
    ]
